### ISSUE TITLE
c* = E(sk, m0)?

### ISSUE THREAD

**Issue by gursev** [lgarron/crypto.graphics#5]
If the challenger returns c* = E(sk, mb), b in {0,1}, the attacker will be able to easily decrypt the message and get the value of b. Should it be E(pk, mb) instead?

**Comment by lgarron** [comment]
You're right, that's a copy-paste typo.

**Comment by lgarron** [comment]
> c* = E(sk, mb)

Note that this doesn't make sense in the context of these definition. The secret key of an `IND-CCA{1,2}` scheme cannot be used to encrypt.

(In the real world, this is a bit more muddled, since a PGP "key" contains multiple keys.)
